### PR TITLE
Adding Kris Hatcher Presentation Info

### PR DESCRIPTION
**Pull request by krishatcher**

### CODE REVIEW

**Comment by ardalis** [comment]
closed why?

**Comment by krishatcher** [comment]
Someone updated the README to add who each talk was by, along with their twitter handle.  I had to do that to my README update as well.

**Comment by ardalis** [comment]
yeah, that was me, sorry. All good now, thanks!

**Comment by ardalis** [comment]
though, you did misspell your name on the README...

**Comment by ardalis** [comment]
(fixed now)

**Pull request closed without merging**
